name: PlexBot

services:
  plexbot:
    container_name: PlexBot
    image: ghcr.io/plexbot/plexbot:latest
    build:
      context: ../..
      dockerfile: Install/Docker/dockerfile
    restart: unless-stopped
    volumes:
      - ../..:/source
      - ../../data:/app/data
      - ../../logs:/app/logs
      - ../../.env:/app/.env
      - ../../Images:/app/Images
    environment:
      - DOTNET_ENVIRONMENT=Production
      - EXTENSIONS_SOURCE_DIR=/source/Extensions
    env_file:
      - ../../.env
    networks:
      - plexbot-network

networks:
  plexbot-network:
    name: plexbot-network
    driver: bridge
